### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by Readdeo** [richardasaurus/mega.py#86]
Hi!
Icant install mega.py with pip. This is the result in the console:

`creating build/temp.linux-x86_64-3.5/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.5m -c src/MD2.c -o build/temp.linux-x86_64-3.5/src/MD2.o
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9lom3qp7/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4d128x_h-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-9lom3qp7/pycrypto/
`

Do you have any suggestions?

**Comment by snabb** [comment]
yum install redhat-rpm-config

**Comment by Readdeo** [comment]
Thank you for your response but still can't install after  "yum install redhat-rpm-config"
